# Generated by Django 4.1.2 on 2022-10-25 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0002_rename_for_doctor_schedule_of_doctor_and_more'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_time', models.DateTimeField()),
                ('type', models.CharField(choices=[('visit', 'Regular Checkup'), ('followup', 'Requested Follow Up'), ('report', 'Report Review'), ('checkup', 'Routined Checkup'), ('operation', 'Operation')], max_length=63)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('of_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('of_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
