# Generated by Django 4.1.2 on 2022-10-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
    ]
